/**
 * Targeting: the difference between "recorded what the model happened to click"
 * and "recorded a verified way to find that control again".
 *
 * RECORD TIME — buildTargetDescriptor():
 *   1. mark the element (temporary attribute) at the model's coordinates
 *   2. probe candidate semantic locators LIVE; a candidate counts only if its
 *      first match IS the marked element
 *   3. primary = best verified candidate; remaining verified = fallbacks;
 *      id + coordinate appended as honest last resorts
 *   4. fingerprint captured for replay-time identity verification
 *
 * REPLAY TIME — resolveDescriptor():
 *   walk candidates in order; verify fingerprint of the resolved element;
 *   only fall back to coordinates when everything semantic failed, marking
 *   the step degraded (never silently).
 */
import type { Frame, Locator, Page } from 'playwright';
import type { ElementFacts } from '../core/actions.js';
import type { Fingerprint, LocatorSpec, TargetDescriptor } from '../core/artifact.js';
import type { PlaywrightWebDriver } from './driver.js';

const FP_PASS_SCORE = 0.6;

// ---------------------------------------------------------------------------
// Record-time descriptor construction
// ---------------------------------------------------------------------------

export async function buildTargetDescriptor(
  driver: PlaywrightWebDriver,
  facts: ElementFacts,
  viewport: { width: number; height: number }
): Promise<TargetDescriptor> {
  const framePath = facts.framePath ?? [];
  // Mark the exact element (frame-local rect center) for live probe verification.
  await driver
    .markElementInFrame(framePath, facts.rect.x + Math.floor(facts.rect.width / 2), facts.rect.y + Math.floor(facts.rect.height / 2))
    .catch(() => false);

  const verified = new Set<string>();
  const probes: Array<{ key: string; spec: LocatorSpec }> = [];

  if (facts.role && isSemanticRole(facts.role) && facts.accessibleName) {
    probes.push({
      key: `role-exact:${facts.role}|${norm(facts.accessibleName)}`,
      spec: { kind: 'role', role: facts.role, name: facts.accessibleName, exact: true },
    });
    probes.push({
      key: `role-substr:${facts.role}|${norm(facts.accessibleName)}`,
      spec: { kind: 'role', role: facts.role, name: facts.accessibleName, exact: false },
    });
  }
  if (isInputLike(facts) && facts.accessibleName) {
    probes.push({ key: `label:${norm(facts.accessibleName)}`, spec: { kind: 'label', text: facts.accessibleName } });
  }
  if (facts.placeholder) {
    probes.push({ key: `placeholder:${norm(facts.placeholder)}`, spec: { kind: 'placeholder', text: facts.placeholder } });
  }
  if (facts.title) {
    probes.push({ key: `title:${norm(facts.title)}`, spec: { kind: 'title', text: facts.title } });
  }
  if (facts.visibleText && !isInputLike(facts)) {
    probes.push({
      key: `text-exact:${norm(facts.visibleText)}`,
      spec: { kind: 'text', text: facts.visibleText.slice(0, 60), exact: true },
    });
  }
  if (facts.nameAttr) {
    probes.push({ key: `name:${facts.nameAttr}`, spec: { kind: 'name', name: facts.nameAttr } });
  }
  if (facts.id) {
    probes.push({ key: `id:${facts.id}`, spec: { kind: 'id', id: facts.id, note: 'legacy autogenerated id' } });
  }

  for (const p of probes) {
    const ok = await probeSpec(driver, framePath, p.spec).catch(() => false);
    if (ok) verified.add(p.key);
  }

  const ordered: LocatorSpec[] = [];
  let quality: TargetDescriptor['quality'] = 'coordinate-only';
  for (const p of probes) {
    if (verified.has(p.key)) ordered.push(p.spec);
  }
  if (ordered.length > 0) {
    const first: LocatorSpec | undefined = ordered[0];
    quality = first && first.kind === 'id' ? 'partial' : 'verified';
  }
  await driver.clearProbeMarks();

  const coordinate: LocatorSpec = {
    kind: 'coordinate',
    // FRAME-LOCAL pixels of the control's center — replay translates through
    // the frame's viewport origin. Grid spaces mixed with frame offsets proved
    // ambiguous (see knowledge log), so we keep raw local pixels.
    x: facts.rect.x + Math.floor(facts.rect.width / 2),
    y: facts.rect.y + Math.floor(facts.rect.height / 2),
    note: 'last resort; frame-local pixel center at record time',
  };

  const fallbacks: LocatorSpec[] = [...ordered.slice(1)];
  fallbacks.push(...(facts.id ? [] : []));
  fallbacks.push(coordinate);

  return {
    primary: ordered[0] ?? coordinate,
    fallbacks,
    scope: { framePath },
    fingerprint: fingerprintOf(facts),
    quality: ordered.length > 0 ? quality : 'coordinate-only',
    rationale:
      ordered.length > 0
        ? `${ordered.length} semantic locator(s) verified against the live element at record time`
        : 'no semantic locator verified at record time; coordinates recorded as explicit last resort',
  };
}

async function probeSpec(driver: PlaywrightWebDriver, framePath: string[], spec: LocatorSpec): Promise<boolean> {
  switch (spec.kind) {
    case 'role':
      return driver.probeCandidate(framePath, { kind: 'role', role: spec.role, name: spec.name, exact: spec.exact });
    case 'label':
      return driver.probeCandidate(framePath, { kind: 'label', name: spec.text, exact: spec.exact });
    case 'text':
      return driver.probeCandidate(framePath, { kind: 'text', name: spec.text, exact: spec.exact });
    case 'placeholder':
      return driver.probeCandidate(framePath, { kind: 'placeholder', name: spec.text });
    case 'title':
      return driver.probeCandidate(framePath, { kind: 'title', name: spec.text, exact: true });
    case 'name':
      return driver.probeSelector(framePath, `[name="${cssEscape(spec.name)}"]`);
    case 'id':
      return driver.probeId(framePath, spec.id);
    default:
      return false; // value/coordinate never probed semantically
  }
}

function isSemanticRole(role: string): boolean {
  return [
    'button', 'link', 'textbox', 'searchbox', 'combobox', 'checkbox', 'radio',
    'menuitem', 'tab', 'option', 'heading', 'table',
  ].includes(role);
}

function isInputLike(facts: ElementFacts): boolean {
  return ['input', 'textarea', 'select'].includes(facts.tag);
}

function norm(s: string): string {
  return s.replace(/\s+/g, ' ').trim().slice(0, 80);
}

function fingerprintOf(facts: ElementFacts): Fingerprint {
  const fp: Fingerprint = { tag: facts.tag };
  if (facts.id) fp.idPattern = normalizeIdPattern(facts.id);
  if (facts.accessibleName) fp.accessibleName = facts.accessibleName.slice(0, 80);
  fp.ordinalInParent = facts.ordinalInParent;
  const attrs: Record<string, string> = {};
  if (facts.nameAttr) attrs['name'] = facts.nameAttr;
  if (facts.typeAttr) attrs['type'] = facts.typeAttr;
  if (Object.keys(attrs).length) fp.attributes = attrs;
  return fp;
}

/** Legacy ASP.NET ids are version-stable modulo counters: ctl02 → ctl{N}. */
function normalizeIdPattern(id: string): string {
  return id.replace(/ctl\d+/g, 'ctl{N}').replace(/\d+/g, '{D}');
}

// ---------------------------------------------------------------------------
// Replay-time resolution
// ---------------------------------------------------------------------------

export interface ResolutionOutcome {
  status: 'resolved' | 'coordinate-fallback' | 'not-found';
  locator?: Locator;
  usedFallbackIndex: number | null; // null => primary
  fingerprintScore?: number;
  degraded: boolean;
  attempts: Array<{ spec: LocatorSpec; why: string }>;
}

export function resolveFrameByPath(page: Page, path: string[]): Frame {
  let frame: Frame = page.mainFrame();
  for (const name of path) {
    const next = frame.childFrames().find((f) => f.name() === name || f.url() === name);
    if (!next) break;
    frame = next;
  }
  return frame;
}

/** Fail-closed frame resolution: null when ANY path segment is missing.
 *  Silent fallback to a parent frame once made replay act on the wrong
 *  surface after a session-expiry redirect — never again. */
export function resolveFrameByPathStrict(page: Page, path: string[]): Frame | null {
  let frame: Frame = page.mainFrame();
  for (const name of path) {
    const next = frame.childFrames().find((f) => f.name() === name || f.url() === name);
    if (!next) return null;
    frame = next;
  }
  return frame;
}

export async function resolveDescriptor(
  page: Page,
  desc: TargetDescriptor,
  opts: { timeoutMs?: number; skipCoordinateFallback?: boolean } = {}
): Promise<ResolutionOutcome> {
  const timeoutMs = opts.timeoutMs ?? 8000;
  const frame = resolveFrameByPath(page, desc.scope.framePath ?? []);
  const root: Frame | Locator = desc.scope.container
    ? translateSpec(frame, desc.scope.container)
    : frame;

  const attempts: ResolutionOutcome['attempts'] = [];
  const specs: Array<{ spec: LocatorSpec | null; label: string }> = [
    { spec: desc.primary, label: 'primary' },
    ...desc.fallbacks.map((f) => ({ spec: f, label: 'fallback' })),
  ];

  let index = -1;
  for (const entry of specs) {
    index += 1;
    const spec = entry.spec;
    if (!spec) continue;
    if (spec.kind === 'coordinate') {
      if (opts.skipCoordinateFallback) continue;
      attempts.push({ spec, why: 'coordinate last resort' });
      return {
        status: 'coordinate-fallback',
        usedFallbackIndex: index,
        degraded: true,
        attempts,
      };
    }
    try {
      const loc = translateSpec(root as Frame, spec);
      await loc.first().waitFor({ state: 'visible', timeout: timeoutMs });
      if (desc.fingerprint) {
        const score = await scoreAgainstFingerprint(loc.first(), desc.fingerprint);
        if (score >= FP_PASS_SCORE) {
          attempts.push({ spec, why: `fingerprint ${score.toFixed(2)}` });
          return { status: 'resolved', locator: loc.first(), usedFallbackIndex: index === 0 ? null : index, fingerprintScore: score, degraded: false, attempts };
        }
        attempts.push({ spec, why: `fingerprint too low (${score.toFixed(2)})` });
        continue;
      }
      attempts.push({ spec, why: 'no fingerprint to verify' });
      return { status: 'resolved', locator: loc.first(), usedFallbackIndex: index === 0 ? null : index, degraded: false, attempts };
    } catch (err) {
      attempts.push({ spec, why: shortErr(err) });
      continue;
    }
  }

  return {
    status: 'not-found',
    usedFallbackIndex: null,
    degraded: true,
    attempts,
  };
}

function translateSpec(root: Frame | Locator, spec: LocatorSpec): Locator {
  const base = root as Frame;
  switch (spec.kind) {
    case 'role': {
      const r = base.getByRole(spec.role as Parameters<Frame['getByRole']>[0], {
        name: spec.name,
        exact: spec.exact ?? false,
      });
      return spec.exact ? r : r;
    }
    case 'label':
      return base.getByLabel(spec.text, { exact: spec.exact ?? false });
    case 'text':
      return base.getByText(spec.text, { exact: spec.exact ?? false });
    case 'placeholder':
      return base.getByPlaceholder(spec.text);
    case 'title':
      return base.getByTitle(spec.text, { exact: true });
    case 'name':
      return base.locator(`[name="${cssEscape(spec.name)}"]`);
    case 'id':
      return base.locator(`#${cssEscape(spec.id)}`);
    case 'value':
      return base.locator(`[value="${cssEscape(spec.text)}"]`);
    case 'coordinate':
      throw new Error('coordinate specs never translate to locators');
  }
}

async function scoreAgainstFingerprint(locator: Locator, fp: Fingerprint): Promise<number> {
  const facts = await locator
    .evaluate((el) => {
      const accName =
        el.getAttribute('aria-label') ||
        ((el as HTMLInputElement).value && ['submit', 'button', 'reset'].includes((el as HTMLInputElement).type)
          ? (el as HTMLInputElement).value
          : '') ||
        (el as HTMLElement).innerText?.slice(0, 80) ||
        '';
      return {
        tag: el.tagName.toLowerCase(),
        id: el.id || '',
        accessibleName: accName.replace(/\s+/g, ' ').trim(),
        ordinalInParent: el.parentElement ? Array.prototype.indexOf.call(el.parentElement.children, el) : -1,
        nameAttr: el.getAttribute('name') || '',
        typeAttr: el.getAttribute('type') || '',
      };
    })
    .catch(() => null);
  if (!facts) return 0;
  let score = 0;
  if (fp.tag && fp.tag === facts.tag) score += 0.3;
  if (fp.idPattern && facts.id && idPatternMatches(fp.idPattern, facts.id)) score += 0.25;
  if (fp.accessibleName && facts.accessibleName.toLowerCase().includes(fp.accessibleName.toLowerCase().slice(0, 24))) {
    score += 0.2;
  }
  if (fp.ordinalInParent !== undefined && fp.ordinalInParent === facts.ordinalInParent) score += 0.15;
  if (fp.attributes) {
    for (const [k, v] of Object.entries(fp.attributes)) {
      if ((k === 'name' && facts.nameAttr === v) || (k === 'type' && facts.typeAttr === v)) score += 0.05;
    }
  }
  return Math.min(1, score);
}

/** Legacy id patterns: {N} → \d+ (ctl counter), {D} → \d+. Placeholders are
 *  protected with sentinels so escaping never clobbers them. */
export function idPatternMatches(pattern: string, id: string): boolean {
  const src =
    '^' +
    pattern
      .replace(/\{N\}/g, '\x00N\x00')
      .replace(/\{D\}/g, '\x00D\x00')
      .replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
      .replace(/\x00N\x00/g, '\\d+')
      .replace(/\x00D\x00/g, '\\d+') +
    '$';
  try {
    return new RegExp(src).test(id);
  } catch {
    return false;
  }
}

function cssEscape(s: string): string {
  return s.replace(/([^a-zA-Z0-9_-])/g, '\\$1');
}

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, v));
}

function shortErr(err: unknown): string {
  const msg = err instanceof Error ? err.message : String(err);
  return msg.split('\n')[0]?.slice(0, 120) ?? 'error';
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

/** Resolve {{path.to.value}} templates from a nested context. Unknown refs stay literal. */
export function interpolate(template: string, ctx: unknown): string {
  return template.replace(/\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}/g, (_m, path: string) => {
    const val = lookup(ctx, path);
    return val === undefined ? `{{${path}}}` : String(val);
  });
}

function lookup(obj: unknown, dottedPath: string): unknown {
  let cur: unknown = obj;
  for (const seg of dottedPath.split('.')) {
    if (cur === null || cur === undefined) return undefined;
    if (typeof cur !== 'object') return undefined;
    cur = (cur as Record<string, unknown>)[seg];
  }
  return cur;
}
