/**
 * LegacyBank — hostile legacy core-banking simulator.
 * Data model + tenant configurations.
 *
 * Deliberately hostile surface properties (see REPORT.md):
 *  - ASP.NET WebForms-style autogenerated control names (ctl00$ContentPlaceHolder1$...)
 *  - no semantic classes, no data-testid, table-based layout, <frameset> shell
 *  - two tenants running the SAME vendor product, configured differently
 */

export interface TenantConfig {
  id: string;
  pathPrefix: string;
  institutionName: string;
  vendorProduct: string;
  themeColor: string;
  /** Labels that differ between tenants of the same product — drives variant overrides. */
  labels: {
    signInButton: string;
    memberIdLabel: string;
    searchButton: string;
    membersNavLink: string;
    resultsHeading: string;
    openSubAccountLink: string;
    confirmButton: string;
  };
}

export const TENANTS: Record<string, TenantConfig> = {
  acme: {
    id: 'acme',
    pathPrefix: '/acme',
    institutionName: 'ACME Federal Credit Union',
    vendorProduct: 'CoreVision Suite 2.3',
    themeColor: '#1a6b3c',
    labels: {
      signInButton: 'Sign In',
      memberIdLabel: 'Member ID:',
      searchButton: 'Find Member',
      membersNavLink: 'Member Search',
      resultsHeading: 'Search Results',
      openSubAccountLink: 'Open Sub-Account',
      confirmButton: 'Confirm Opening',
    },
  },
  nw: {
    id: 'nw',
    pathPrefix: '/nw',
    institutionName: 'NorthWind Community Credit Union',
    vendorProduct: 'CoreVision Suite 2.4',
    themeColor: '#1f3a6b',
    labels: {
      signInButton: 'Login',
      memberIdLabel: 'Member Number:',
      searchButton: 'Search',
      membersNavLink: 'Members',
      resultsHeading: 'Member Inquiry Results',
      openSubAccountLink: 'New Sub-Account',
      confirmButton: 'Submit & Confirm',
    },
  },
};

export interface Account {
  type: 'Savings' | 'Checking' | 'Money Market';
  number: string;
  balance: string;
}

export interface Member {
  id: string;
  firstName: string;
  lastName: string;
  status: 'Active' | 'Locked';
  since: string;
  accounts: Account[];
  locked?: boolean;
}

export const MEMBERS: Member[] = [
  {
    id: 'M10041',
    firstName: 'Jane',
    lastName: 'Dougherty',
    status: 'Active',
    since: '03/14/2011',
    accounts: [
      { type: 'Savings', number: '0001234567', balance: '$2,450.75' },
      { type: 'Checking', number: '0007654321', balance: '$310.20' },
    ],
  },
  {
    id: 'M10087',
    firstName: 'Marcus',
    lastName: 'Bell',
    status: 'Active',
    since: '07/02/2015',
    accounts: [{ type: 'Savings', number: '0002345678', balance: '$10,234.10' }],
  },
  {
    id: 'M10113',
    firstName: 'Priya',
    lastName: 'Natarajan',
    status: 'Active',
    since: '11/19/2018',
    accounts: [
      { type: 'Savings', number: '0003456789', balance: '$88.05' },
      { type: 'Checking', number: '0009876543', balance: '$1,500.00' },
    ],
  },
  {
    id: 'M10999',
    firstName: 'Compliance',
    lastName: 'Hold',
    status: 'Locked',
    since: '01/01/2020',
    accounts: [],
    locked: true,
  },
];

/** Demo credentials (simulator only — still treated as sensitive by DEFT's redactor). */
export const DEMO_USER = { userId: 'teller1', password: 'Demo!2345' };

export function findMember(id: string): Member | undefined {
  return MEMBERS.find((m) => m.id.toUpperCase() === id.trim().toUpperCase());
}
