/**
 * Capability Artifact schema — the load-bearing contract of the system.
 *
 * A capability is what an AI agent invokes in production: a typed, versioned,
 * reviewable description of a UI flow. Zod is the single source of truth:
 * static types + runtime validation + JSON Schema export (for humans and
 * external agents) all derive from these definitions.
 */
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Targeting
// ---------------------------------------------------------------------------

/** Normalized 0-999 coordinate space used by vision planners (see REPORT). */
export const GridPoint = z.object({ x: z.number().int().min(0).max(999), y: z.number().int().min(0).max(999) }).strict();
export type GridPoint = z.infer<typeof GridPoint>;

/**
 * One way to find a control. `kind` maps to a semantic Playwright locator.
 * Coordinate is legal ONLY as a fallback — replay through it is flagged degraded.
 */
export const LocatorSpec = z.discriminatedUnion('kind', [
  z.object({
    kind: z.literal('role'),
    role: z.string().min(1),
    name: z.string().min(1),
    exact: z.boolean().optional(),
  }).strict(),
  z.object({ kind: z.literal('label'), text: z.string().min(1), exact: z.boolean().optional() }).strict(),
  z.object({ kind: z.literal('text'), text: z.string().min(1), exact: z.boolean().optional() }).strict(),
  z.object({ kind: z.literal('placeholder'), text: z.string().min(1) }).strict(),
  z.object({ kind: z.literal('title'), text: z.string().min(1) }).strict(),
  /**
   * Legacy WebForms canonical targeting: the `name` attribute is the postback
   * key and is version-stable even when autogenerated ids churn.
   */
  z.object({ kind: z.literal('name'), name: z.string().min(1), note: z.string().optional() }).strict(),
  /** Legacy fallback: vendor-stable autogenerated ids (ctl00$...). Brittle across versions. */
  z.object({ kind: z.literal('id'), id: z.string().min(1), note: z.string().optional() }).strict(),
  z.object({ kind: z.literal('value'), text: z.string() }).strict(),
  /**
   * Explicit coordinate space — the two historical encodings used the same
   * shape with different semantics, which was a real bug source.
   *  - frame-px:      pixels relative to the frame named by scope.framePath
   *  - viewport-grid: 0-999 grid over the full viewport (planner hints)
   */
  z.object({
    kind: z.literal('coordinate'),
    space: z.enum(['frame-px', 'viewport-grid']).default('frame-px'),
    x: z.number().int().min(0),
    y: z.number().int().min(0),
    note: z.string().optional(),
  }).strict(),
]);
export type LocatorSpec = z.infer<typeof LocatorSpec>;

/** Stable-ish properties captured at record time, used to VERIFY identity at replay time. */
export const Fingerprint = z
  .object({
    tag: z.string().optional(),
    idPattern: z.string().optional(), // regex; legacy ids like ctl00$..._btnSearch are normalized
    accessibleName: z.string().optional(), // computed accessible name at record time
    ordinalInParent: z.number().int().nonnegative().optional(),
    attributes: z.record(z.string(), z.string()).optional(),
  })
  .strict();
export type Fingerprint = z.infer<typeof Fingerprint>;

export const TargetDescriptor = z.object({
  primary: LocatorSpec,
  fallbacks: z.array(LocatorSpec).default([]),
  scope: z
    .object({
      /** Frame chain from page root, e.g. ["topFrame","content"]. Empty = main frame. */
      framePath: z.array(z.string()).default([]),
      /** Optional ancestor constraint to disambiguate repeated labels. */
      container: LocatorSpec.optional(),
    })
    .strict().default({ framePath: [] }),
  fingerprint: Fingerprint.optional(),
  /**
   * How well this targeting was verified AT RECORD TIME:
   *  - verified: a semantic locator was proven to match exactly the recorded element
   *  - partial: only weaker evidence (e.g. text match without role confirmation)
   *  - coordinate-only: no semantic locator verified; replay through it is degraded
   */
  quality: z.enum(['verified', 'partial', 'coordinate-only']).default('verified'),
  /** Why this targeting was chosen — surfaced to reviewers. */
  rationale: z.string().optional(),
}).strict();
export type TargetDescriptor = z.infer<typeof TargetDescriptor>;

// ---------------------------------------------------------------------------
// Checks, recovery
// ---------------------------------------------------------------------------

export const Check = z.discriminatedUnion('assert', [
  z.object({ assert: z.literal('urlMatchesGlob'), pattern: z.string().min(1) }).strict(),
  z.object({ assert: z.literal('elementVisible'), target: TargetDescriptor, timeoutMs: z.number().int().positive().default(10000) }).strict(),
  z.object({ assert: z.literal('elementTextContains'), target: TargetDescriptor, text: z.string().min(1), timeoutMs: z.number().int().positive().default(10000) }).strict(),
  z.object({ assert: z.literal('pageTextContains'), text: z.string().min(1) }).strict(),
]);
export type Check = z.infer<typeof Check>;

/**
 * Environment bindings resolve templates like {{env.username}} or {{baseUrl}}
 * WITHOUT ever persisting secret material inside the artifact.
 */
export const EnvBinding = z.discriminatedUnion('source', [
  z.object({ source: z.literal('literal'), value: z.string() }).strict(),
  z.object({ source: z.literal('envVar'), name: z.string().min(1), sensitive: z.boolean().default(false) }).strict(),
]);
export type EnvBinding = z.infer<typeof EnvBinding>;

/**
 * Bounded, auditable recovery for legitimate runtime conditions.
 * A rule fires at most maxAttempts times per run; every attempt lands in
 * evidence. Actions form a short chain (e.g. session-expired → re-login).
 */
export const RecoverAction = z.discriminatedUnion('action', [
  z.object({ action: z.literal('navigate'), urlTemplate: z.string().min(1), riskClass: z.enum(['safe', 'risky']), idempotent: z.boolean(), expectsDialog: z.boolean() }).strict(),
  z.object({ action: z.literal('click'), target: TargetDescriptor, riskClass: z.enum(['safe', 'risky']), idempotent: z.boolean(), expectsDialog: z.boolean() }).strict(),
  z.object({ action: z.literal('fill'), target: TargetDescriptor, valueTemplate: z.string().min(1), riskClass: z.enum(['safe', 'risky']), idempotent: z.boolean(), expectsDialog: z.boolean() }).strict(),
  z.object({ action: z.literal('select'), target: TargetDescriptor, optionTextTemplate: z.string().min(1), riskClass: z.enum(['safe', 'risky']), idempotent: z.boolean(), expectsDialog: z.boolean() }).strict(),
  z.object({ action: z.literal('wait'), durationMs: z.number().int().positive().max(30000), riskClass: z.enum(['safe', 'risky']), idempotent: z.boolean(), expectsDialog: z.boolean() }).strict(),
  /** Navigate the failed step's frame (or top) back to step.pageUrl. */
  z.object({ action: z.literal('gotoStepPage'), riskClass: z.enum(['safe', 'risky']), idempotent: z.boolean(), expectsDialog: z.boolean() }).strict(),
]);
export type RecoverAction = z.infer<typeof RecoverAction>;

export const RecoverRule = z.object({
  description: z.string().min(3),
  // Only conditions the engine actually evaluates — schema honesty over breadth.
  when: z
    .object({
      redirectedToGlob: z.string().optional(),
      errorClass: z.string().optional(),
    })
    .strict().refine((w) => Object.values(w).some(Boolean), { message: 'when needs at least one condition' }),
  do: z.array(RecoverAction).min(1).max(5),
  maxAttempts: z.number().int().min(1).max(3).default(1),
}).strict();
/**
 * A rule may either inline its action chain or reference a named chain in
 * artifact.recoveryChains — shared recovery logic without per-step bloat.
 */
export const RecoverSpec = z.union([
  RecoverRule,
  z.object({ chainRef: z.string().min(1), description: z.string().optional() }).strict(),
]);
export type RecoverSpec = z.infer<typeof RecoverSpec>;

// ---------------------------------------------------------------------------
// Steps & extraction
// ---------------------------------------------------------------------------

export const StepAction = z.enum([
  'navigate',
  'click',
  'fill',
  'select',
  'press',
  'scroll',
  'wait',
  'extract',
  'check',
]);
export type StepAction = z.infer<typeof StepAction>;

/** Relational extraction from hostile tables — robust to row reordering. */
export const TableExtract = z.object({
  strategy: z.literal('tableCell'),
  scope: z
    .object({
      framePath: z.array(z.string()).default([]),
      container: LocatorSpec.optional(),
    })
    .strict().default({ framePath: [] }),
  rowMatch: z.object({
    columnHeader: z.string().min(1),
    equalsTemplate: z.string().optional(),
    containsTemplate: z.string().optional(),
  }).strict(),
  columnHeader: z.string().min(1),
}).strict();

export const TextExtract = z.object({
  strategy: z.literal('text'),
  target: TargetDescriptor,
  /** First capture group is returned when present. */
  regexWithGroups: z.string().optional(),
}).strict();
export type TableExtract = z.infer<typeof TableExtract>;
export type TextExtract = z.infer<typeof TextExtract>;

export const Step = z.object({
  id: z.string().regex(/^[a-z0-9_.-]+$/i).min(2),
  /** Human-readable intent — makes the artifact reviewable without code reading. */
  intent: z.string().min(3),
  action: StepAction,
  target: TargetDescriptor.optional(),
  /** Template string; may reference {{inputs.*}}, {{env.*}}, {{target.*}}, prior outputs {{outputs.*}}. */
  valueTemplate: z.string().optional(),
  /** Page URL (template) where this step executes — lets recovery chains
   *  return the flow to the right page after a mid-flow re-login. */
  pageUrl: z.string().optional(),
  selectOptionText: z.string().optional(),
  keyCombo: z.string().optional(),
  /** Explicit wait duration used by guarded recovery wait actions. */
  waitDurationMs: z.number().int().positive().max(30000).optional(),
  scrollDirection: z.enum(['up', 'down']).optional(),
  postCheck: Check.optional(),
  /**
   * Replay-safety semantics. Non-idempotent steps (submits, transfers) are
   * NEVER re-executed by recovery fast-forward — re-running them could
   * duplicate financial side effects.
   */
  idempotent: z.boolean().default(true),
  /**
   * Declares that this step EXPECTS a native dialog (confirm/alert) and the
   * engine should ACCEPT it. Default: all dialogs are DISMISSED (safe default
   * — infrastructure never auto-accepts an unexpected irreversible confirm).
   */
  expectsDialog: z.boolean().default(false),
  recoverableErrors: z.array(RecoverSpec).max(4).default([]),
  riskClass: z.enum(['safe', 'risky']).default('safe'),
  // extract-only fields:
  outputKey: z.string().optional(),
  extract: z.union([TableExtract, TextExtract]).optional(),
}).strict();
export type Step = z.infer<typeof Step>;

// ---------------------------------------------------------------------------
// Outcomes & top-level artifact
// ---------------------------------------------------------------------------

/**
 * Expected business results the CALLER must hear about ("no such member" is an
 * answer, not a crash). Detection patterns turn matching step failures into a
 * declared outcome instead of a failure.
 */
export const BusinessOutcome = z.object({
  code: z.string().regex(/^[A-Z][A-Z0-9_]+$/),
  description: z.string().min(3),
  detect: z.object({
    duringStepId: z.string().optional(),
    pageTextContains: z.string().optional(),
    dialogTextContains: z.string().optional(),
    urlGlob: z.string().optional(),
  }).strict().refine((d) => Object.values(d).some(Boolean), { message: 'detect needs at least one pattern' }),
  returnsToCaller: z.record(z.string(), z.unknown()).default({}),
}).strict();
export type BusinessOutcome = z.infer<typeof BusinessOutcome>;

export const RiskPolicy = z
  .object({
    /** What to do when a risky (irreversible) step is reached during unattended replay. */
    onRiskyStep: z.enum(['require_approval', 'allow']).default('require_approval'),
    rationale: z.string().optional(),
  }).strict()
  .default({ onRiskyStep: 'require_approval' });

/** Tenant-specific overlay for artifacts shared across institutions. */
export const Variant = z.object({
  id: z.string().min(1),
  match: z.object({ tenantId: z.string().min(1) }).strict(),
  /** Flat-key patches, e.g. "steps[s4].target.primary.name": "Find Member". */
  patches: z.record(z.string(), z.unknown()).default({}),
  notes: z.string().optional(),
}).strict();
export type Variant = z.infer<typeof Variant>;

export const Provenance = z.object({
  discoveredFromRunId: z.string().optional(),
  /** Null/absent for operator-authored capabilities (no planner involved). */
  plannerModel: z.string().nullable().optional(),
  recordedAt: z.string().datetime().optional(),
  stepCount: z.number().int().nonnegative().optional(),
  validation: z
    .object({
      lastReplayAt: z.string().datetime().nullable().default(null),
      lastReplayStatus: z.enum(['SUCCESS', 'BUSINESS_OUTCOME', 'FAILED']).nullable().default(null),
      replaySuccessCount: z.number().int().nonnegative().default(0),
      replayFailureCount: z.number().int().nonnegative().default(0),
    })
    .strict().default({
      lastReplayAt: null,
      lastReplayStatus: null,
      replaySuccessCount: 0,
      replayFailureCount: 0,
    }),
}).strict();
export type Provenance = z.infer<typeof Provenance>;

type JsonSchemaRecord = Record<string, unknown>;

/** Output JSON Schema with fail-closed object contracts at every depth. */
export const OutputSchema = z.record(z.string(), z.unknown()).superRefine((schema, ctx) => {
  const unsupportedKeywords = [
    '$ref', '$defs', 'definitions', 'oneOf', 'anyOf', 'allOf', 'not', 'if', 'then', 'else',
    'prefixItems', 'contains', 'dependentSchemas', 'patternProperties', 'unevaluatedProperties',
  ];
  const visit = (node: unknown, path: (string | number)[], ancestors: Set<object>): void => {
    if (!node || typeof node !== 'object' || Array.isArray(node)) return;
    const record = node as JsonSchemaRecord;
    if (ancestors.has(record)) {
      ctx.addIssue({ code: 'custom', path, message: 'cyclic output schema is not supported' });
      return;
    }
    const nextAncestors = new Set(ancestors);
    nextAncestors.add(record);

    const structuralKeys = ['properties', 'required', 'additionalProperties'];
    if (!('type' in record)) {
      ctx.addIssue({ code: 'custom', path, message: 'output schemas require an explicit type' });
    } else if (structuralKeys.some((key) => key in record) && record.type !== 'object') {
      ctx.addIssue({ code: 'custom', path, message: 'properties/required/additionalProperties require type object' });
    }

    for (const keyword of unsupportedKeywords) {
      if (Object.prototype.hasOwnProperty.call(record, keyword)) {
        ctx.addIssue({ code: 'custom', path: [...path, keyword], message: `unsupported output schema keyword: ${keyword}` });
      }
    }

    if (record.type === 'object') {
      const properties = record.properties;
      if (!properties || typeof properties !== 'object' || Array.isArray(properties)) {
        ctx.addIssue({ code: 'custom', path, message: 'object output schemas require properties' });
      } else {
        const propertyKeys = Object.keys(properties as JsonSchemaRecord).sort();
        const required = Array.isArray(record.required)
          ? record.required.filter((key): key is string => typeof key === 'string')
          : [];
        if (required.length !== new Set(required).size || [...required].sort().join('\0') !== propertyKeys.join('\0')) {
          ctx.addIssue({ code: 'custom', path: [...path, 'required'], message: 'required must exactly cover output properties' });
        }
        if (record.additionalProperties !== false) {
          ctx.addIssue({ code: 'custom', path: [...path, 'additionalProperties'], message: 'additionalProperties must be false' });
        }
        for (const [key, child] of Object.entries(properties as JsonSchemaRecord)) {
          visit(child, [...path, 'properties', key], nextAncestors);
        }
      }
    }

    if (record.type === 'array') {
      if (!('items' in record)) {
        ctx.addIssue({ code: 'custom', path, message: 'array output schemas require items' });
      } else {
        visit(record.items, [...path, 'items'], nextAncestors);
      }
    }
  };

  visit(schema, [], new Set());
});
export type OutputSchema = z.infer<typeof OutputSchema>;

export const CapabilityArtifactSchema = z.object({
  schemaVersion: z.literal('1'),
  kind: z.literal('Capability'),
  metadata: z.object({
    id: z.string().regex(/^[a-z0-9]+([.-][a-z0-9]+)*\.[a-z0-9]+([.-][a-z0-9]+)*$/, 'id must be <appfamily>.<capability>'),
    name: z.string().min(3),
    description: z.string().min(10),
    version: z.string().regex(/^\d+\.\d+\.\d+$/),
    status: z.enum(['draft', 'approved', 'needs-review', 'deprecated']).default('draft'),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
  }).strict(),
  target: z.object({
    appFamily: z.string().min(1),
    surfaceType: z.enum(['web-modern', 'web-legacy', 'desktop']),
    entryUrlTemplate: z.string().min(1),
    variants: z.array(Variant).default([]),
  }).strict(),
  inputs: z.record(z.string(), z.unknown()), // JSON Schema (draft 2020-12)
  outputs: OutputSchema,
  environmentBindings: z.record(z.string(), EnvBinding).default({}),
  steps: z.array(Step).min(1),
  /**
   * Deterministic authentication phase, executed by the ENGINE before the
   * planner ever observes the surface (discovery) and before capability steps
   * (replay). Credential values live only in environment bindings — they are
   * resolved at runtime and NEVER enter model context.
   */
  authPhase: z.object({ steps: z.array(Step).min(1) }).strict().optional(),
  businessOutcomes: z.array(BusinessOutcome).default([]),
  /** Named, shared recovery action chains referenced by steps via chainRef. */
  recoveryChains: z.record(z.string(), z.array(RecoverAction)).optional(),
  successCondition: z.object({
    allOf: z.array(Check).min(1),
  }).strict(),
  riskPolicy: RiskPolicy,
  redaction: z.object({
    sensitiveInputNames: z.array(z.string()).default([]),
    notes: z.string().default(''),
  }).strict(),
  provenance: Provenance,
}).strict().superRefine((artifact, ctx) => {
  const outputSchema = artifact.outputs as Record<string, unknown>;
  const properties = outputSchema.type === 'object' && outputSchema.properties && typeof outputSchema.properties === 'object'
    ? new Set(Object.keys(outputSchema.properties as Record<string, unknown>))
    : new Set<string>();
  for (const step of [...(artifact.authPhase?.steps ?? []), ...artifact.steps]) {
    if (step.action === 'extract' && !step.extract) ctx.addIssue({ code: 'custom', path: ['steps', step.id, 'extract'], message: 'extract steps require extract specification' });
    if (step.action !== 'extract' && step.extract) ctx.addIssue({ code: 'custom', path: ['steps', step.id, 'extract'], message: 'extract specification is only valid on extract steps' });
    if (step.action === 'extract' && !step.outputKey) ctx.addIssue({ code: 'custom', path: ['steps', step.id, 'outputKey'], message: 'extract steps require outputKey' });
    if (step.action !== 'extract' && step.outputKey) ctx.addIssue({ code: 'custom', path: ['steps', step.id, 'outputKey'], message: 'outputKey is only valid on extract steps' });
    if (step.outputKey && !properties.has(step.outputKey)) ctx.addIssue({ code: 'custom', path: ['steps', step.id, 'outputKey'], message: 'outputKey must be declared in outputs.properties' });
  }
});
export type CapabilityArtifact = z.infer<typeof CapabilityArtifactSchema>;

/** Normalize compiler-proposed object output contracts before artifact parsing. */
export function normalizeOutputSchema(schema: Record<string, unknown>): Record<string, unknown> {
  const normalize = (node: unknown): unknown => {
    if (!node || typeof node !== 'object' || Array.isArray(node)) return node;
    const current = node as Record<string, unknown>;
    const normalized = { ...current };
    if (current.type === 'object' && current.properties && typeof current.properties === 'object' && !Array.isArray(current.properties)) {
      const properties = Object.fromEntries(
        Object.entries(current.properties as Record<string, unknown>).map(([key, child]) => [key, normalize(child)])
      );
      const existingRequired = Array.isArray(current.required)
        ? current.required.filter((key): key is string => typeof key === 'string')
        : [];
      normalized.properties = properties;
      normalized.required = [...new Set([...existingRequired, ...Object.keys(properties)])];
      normalized.additionalProperties = false;
    } else if (current.type === 'array' && 'items' in current) {
      normalized.items = normalize(current.items);
    }
    return normalized;
  };
  return normalize(schema) as Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Replay result contract — the three-way outcome distinction lives HERE.
// ---------------------------------------------------------------------------

export const ReplayStatus = z.enum(['SUCCESS', 'BUSINESS_OUTCOME', 'FAILED']);
export type ReplayStatus = z.infer<typeof ReplayStatus>;

export interface StepTimelineEntry {
  stepId: string;
  intent: string;
  phase: 'wait' | 'locate' | 'act' | 'verify' | 'recover';
  ok: boolean;
  ms: number;
  detail?: string;
  degraded?: boolean;
  recovered?: boolean;
}

export interface FailureDetail {
  stepId: string;
  phase: NonNullable<StepTimelineEntry['phase']>;
  errorClass: string;
  expected: string;
  observed: string;
  evidenceRefs: string[]; // screenshot/log refs under /evidence
}

export interface EscalationInfo {
  interventionId: string;
  reason: string;
  resumedByHuman: boolean;
  /** Audit samples captured while the human held the lease. */
  humanSamplesCaptured: number;
  /** Samples that differed from the previous one — evidence of REAL state
   *  change under human control (not N identical screenshots). */
  humanStateChanges: number;
}

export interface ReplayResult {
  runId: string;
  capabilityId: string;
  capabilityVersion: string;
  /** sha256 of the exact artifact bytes this run executed — audit trail. */
  artifactSha256?: string;
  /** Relative evidence-bundle reference to the exact executed definition bytes. */
  artifactDefinitionRef?: string;
  status: ReplayStatus;
  outputs?: Record<string, unknown>;
  businessOutcome?: { code: string; description: string; returnsToCaller: Record<string, unknown> };
  escalation?: EscalationInfo;
  failure?: FailureDetail;
  timeline: StepTimelineEntry[];
  /** Steps resolved via last-resort coordinate targeting — drift signal. */
  degradedSteps: string[];
  startedAt: string;
  finishedAt: string;
}






